# Generated by Django 6.0.6 on 2026-07-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='photo',
        ),
    ]
